[package]
name = "async_mandelbrot_tokio"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.3"
csv = "1.3.0"
serde = { version = "1.0.201", features = ["derive"] }
toml = "0.8.12"
anyhow = "1.0.83"
tokio = { version = "1.37.0", features = ["full"] }
